### ISSUE TITLE
New font: IBM Plex Mono

### ISSUE THREAD

**Issue by critterverse** [WordPress/twentytwentythree#12]
Can we add the typeface IBM Plex Mono to the font assets? Thank you!

**Comment by colorful-tones** [comment]
@pbking @critterverse  according to my quick research with [Font Scanner plugin](https://www.figma.com/community/plugin/1002875535237160651/FontScanner) in Figma against the TT3 file. IBM Plex Mono: Regular, Light and Bold were used. Hence, I included: Bold, Italic, Regular and Light in #17 . Granted, there is a lot going on in #17 😄 

I _do_ think a larger discussion needs to be had about including fonts and this will impact design. Choosing fonts is nuanced and performance should be considered, which is not always easy for designer to consider. Variable fonts are great, but it is not a clear win in a lot of cases. Here is a simple overview of the issue: [Font Techniques for Modern WordPress Themes](https://wpengine.com/builders/font-techniques-wordpress-themes/)

So, considerations of:

1. Pick only the bare minimum of weights and styles needed
2. Based on the weights and styles: determine if static or variable font is beneficial
3. Only bundle based on first two ☝️ 

I would also encourage us to refrain from loading too many of italic styles, because the browser does a pretty good job of inferring italic without an explicit font file reference. I tend to only include the regular (400) italic as a minimum. 🤔 

<img width="595" alt="Screen Shot 2022-08-11 at 7 04 44 AM" src="https://user-images.githubusercontent.com/405912/184120126-dde73b3b-a96b-404b-9381-9eea14e59a4a.png">

**Comment by pbking** [comment]
I agree wholeheartedly with the above. 

There's also the potential of dynamically loaded fonts (Google Fonts and the like).  Should that be an option the entire font opinion can be an option in each variation.  I'm very keen to see this solution available.

Regardless, the theme's font selection has to be well curated.

Should we have a target total filesize for each?  "As small as possible" can still vary quite a bit across typefaces.

**Comment by carolinan** [comment]
if only the font weights used by the design are included, that can impact the sites when users changes the text appearance.

**Comment by pbking** [comment]
> if only the font weights used by the design are included, that can impact the sites when users changes the text appearance.

That's a good point @carolinan.  It's important to keep the payload small, but also to empower not only the variation designers but also the user who will have no control of what weights are available.

Variable-weight fonts answer that problem the best but that's not an option for all of the fonts.  It sounds like it might be important to include as wide a range of sizes as possible.  Usually I would not feel this way and would be content to only ship the weights needed to achieve the design target.  But for this theme I think the needs are broader than normal.
