### ISSUE TITLE
Variation: "Block-out" (WIP)

### ISSUE THREAD

**Issue by critterverse** [WordPress/twentytwentythree#125]
I've been messing around with a weird idea for a variation that blocks out your images and featured images with a color fill effect, which I was thinking could be a duotone filter that uses ~the same color~ similar colors for the shadow and highlight.

It could look like this:

<img width="1200" alt="tt3-final" src="https://user-images.githubusercontent.com/77359364/187076565-e0df8e5c-8da5-4acd-8a30-4bcf7d7f076c.png">

<img width="600" alt="tt3-colors-final" src="https://user-images.githubusercontent.com/77359364/187076569-75c4d959-f0ab-467b-af68-c93bfe554d4f.png">

Figma: https://www.figma.com/file/1yAfz3sRZoHw1XxNaDPw5N/Block-out-style-variation?node-id=0%3A1

**Comment by critterverse** [comment]
I've changed the colors on the duotone so that the image shows a little bit, figured that might be slightly more practical 😂

^ Updated above and in the Figma!

**Comment by critterverse** [comment]
Here's the theme.json: [block-out.json.zip](https://github.com/WordPress/twentytwentythree/files/9439746/block-out.json.zip)

**Comment by beafialho** [comment]
This style variation has been selected to be bundled with the Twenty Twenty-Three default theme! @critterverse and I have made some tweaks to the submission as a part of the curation process to ensure that all the selected variations work together nicely as a collection. Here are the requested changes:

![Block Out](https://user-images.githubusercontent.com/65220155/188935953-287afe96-e564-4e3c-888c-7d4a5af6d322.png)

- The shadow and highlight colors used in the duotone effect are a bit too close — we’ve updated these colors with more contrast so that the images are slightly more visible.
- New shadow color: #E2161D
- New highlight color: #FF9C9C
- Add duotone effect in more places (site logo, etc)

No explicit next steps are needed — feel free to update theme.json files where relevant or they will be updated in development. Thanks for the contribution!
