### ISSUE TITLE
Variation: "Grapes"

### ISSUE THREAD

**Issue by amjadr360** [WordPress/twentytwentythree#126]
![image](https://user-images.githubusercontent.com/32260742/187008297-33bfadfa-6189-4bad-937b-633ea2be9134.png)

![image](https://user-images.githubusercontent.com/32260742/187008302-c99a1bbb-05c6-47e2-a839-2fd3cf48f0c3.png)![image](https://user-images.githubusercontent.com/32260742/187008307-887ce071-978b-4e8d-939a-f47558d6f0de.png)
![image](https://user-images.githubusercontent.com/32260742/187007437-882249cd-dd12-4843-ae78-65a1699d8d6e.png)

Figma: https://www.figma.com/file/8XBx2sZ6GYYQmdOeOp0tAf/Variation-Grapes?node-id=1%3A164
Variation JSON: [grapes.zip](https://github.com/WordPress/twentytwentythree/files/9437023/grapes.zip)

**Comment by beafialho** [comment]
This style variation has been selected to be bundled with the Twenty Twenty-Three default theme! @critterverse and I have made some tweaks to the submission as a part of the curation process to ensure that all the selected variations work together nicely as a collection. Here are the requested changes:

![Grapes](https://user-images.githubusercontent.com/65220155/188937086-06644798-d39d-4e3d-b726-569f6f964820.png)

- We’ve replaced one of the two green colors for black because they were so similar to each other.

No explicit next steps are needed — feel free to update theme.json files where relevant or they will be updated in development. Thanks for the contribution!
