### ISSUE TITLE
Update testing instructions to require WP 6.1

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#207]
I just tried to test TT3 again with WP 6.0.2, but I see this error message:

> The package could not be installed. Your WordPress version is 6.0.2, however the uploaded theme requires 6.1.

If this is intended, could we please update the testing instructions, so that the "Requirements" lists 6.1 instead of 5.9+? Thanks

![WordPress_twentytwentythree__Twenty_Twenty-Three__the_default_WordPress_theme_sporting_many_styles_that_will_launch_with_WordPress_6_1_](https://user-images.githubusercontent.com/7662449/192327826-0a6e09cc-313b-449d-bfa0-3ce7e52355c2.jpg)

**Comment by mikachan** [comment]
Good shout! We've bumped the version as the theme is in the process of being merged with Core 6.1, but we should've updated this version reference as well. I'll spin up a PR.

For quick testing, if you change the 'Requires at least:' line in the style.css file to 5.9 rather than 6.1, the theme should work again with 6.0.2.
