### ISSUE TITLE
Increase the minimum required WordPress version

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#24]
It is common for the default themes to be compatible with WordPress versions below the version the theme is first included in.

This theme's minimum required version is set to 5.9, but the theme can not be activated on 5.9.3:
```
The package could not be installed. The theme is missing the index.php file.
Theme installation failed.
```
The theme could include an index.php file without causing conflicts for 6.1.
But are there other 6.1 features that are breaking on 5.9?
- The spacing CSS variables are not working. So it depends if you consider that breaking or not.
- "Elements" hover and focus styles do not work.
- Font family options do not work.
- The patterns folder does not work on 5.9. So the theme has no footer and no 404 page content.

Updating templates to include new features like the "no results" block for the queries and the new comments blocks also depends on increasing the version.

**Comment by MaggieCabrera** [comment]
I don't think we followed that rule for TT2, did we @jffng ?

**Comment by jffng** [comment]
We did not, since TT2 was the first block theme and would not work without FSE which shipped with that release.

> It is common for the default themes to be compatible with WordPress versions below the version the theme is first included in.

TT3 is heavily focused on style variations, which shipped with 6.0 I think. Could we bump the minimum required version to 6.0? Since it's quite a plain theme without style variations, I don't see a lot of value to lowering it to 5.9.

**Comment by carolinan** [comment]
6.0 would still mean that the theme can not use the spacing presets or the fluid typography settings.

**Comment by mikachan** [comment]
> 6.0 would still mean that the theme can not use the spacing presets or the fluid typography settings.

This is a great point, I liked the idea of this theme showing examples of using new features like fluid typography and spacing presets. 

Plus if we use anything lower than 6.1, we're going to need to add more CSS.

**Comment by jffng** [comment]
I don't like the idea of adding CSS specifically for 6.0. I think it's okay certain aspects of the theme don't work on 6.0, as long as the lack of those features don't present accessibility issues.

This brings up a question — can TT3 get the `a11y ready` tag if its minimum required version is lower than 6.1? I'm thinking about this [TT2 ticket](https://core.trac.wordpress.org/ticket/55172#comment:28). 

In general, I understand wanting to be more inclusive about the share of folks that can use the theme by lowering the required version, but to me it's kind of an edge case — someone wanting to stay on 5.9 or 6.0 and use TT3. Maybe I'm missing some perspective here though.

**Comment by MaggieCabrera** [comment]
I think block themes are a new paradigm that shouldn't adhere to the rules default classic themes were following just because it's how it's been done. In this case, I don't think it makes sense to support the lower WP versions. It may make sense in a couple of years, when features aren't being added so frequently, but not so much today, specially when the whole point of this theme release is to showcase some of those features.

**Comment by mikachan** [comment]
Based on the above, should we change the minimum version to 6.1?

**Comment by carolinan** [comment]
I think so, but it can't be done yet because then we can't activate it =D

**Comment by mikachan** [comment]
Ohh ha right! 😅
