### ISSUE TITLE
Question about Index template

### ISSUE THREAD

**Issue by dashkevych** [WordPress/twentytwentythree#241]
I am wondering when the Index template (`index.html`) is used/displayed on the user's website with active Twenty Twenty-Three theme.

By default, the theme comes with `home.html`.

This template is shown when "Your homepage displays" in Reading settings is set to "Your latest posts".

If we change Reading settings to "A static page ", where Front page is set to "Homepage", and Blog page is set to "Posts page" then:

 - Front page will display whatever content is added to the page;
 - Blog page will display layout from `home.html`;

There is also `blog-alternative.html`. We can display layout from this template when leaving "Posts page" option empty, and setting the template in the Blog page.

So, does the Index template (`index.html`) is just used as a fallback when the `home.html` is removed from the theme (But since it's not possible to remove the template via the Site Editor, the template must be removed manually from the themes folder in order to index.html to be displayed)?

**Comment by carolinan** [comment]
Index.html is the fallback for all templates, not only home.html.
But yes, the requested template needs to be missing for index.html to be used.

It can not be removed from the theme because WordPress requires it to be included. There is a suggestion to remove that requirement but the requirement has not been removed in WordPress 6.1.
