### ISSUE TITLE
BuddyPress pages blank 

### ISSUE THREAD

**Issue by fernandotellado** [WordPress/twentytwentythree#250]
I've been testing the new theme with WP 6.1-beta2-54351 and BuddyPress pages showed a blank page. These pages work fine with Twenty Twenty-Two, so It shouldn't be a FSE-related issue, isn't it?

**Comment by mikachan** [comment]
This seems to be fixed by adding an empty index.php file to the theme. This used to be a required file in themes, but [since WordPress 6.0](https://core.trac.wordpress.org/ticket/54272), this is no longer a requirement. 

It looks like there is [already a fix](https://buddypress.trac.wordpress.org/changeset/13331) for this in the next version of BuddyPress, 10.5.0. There's some more information in [this ticket](https://buddypress.trac.wordpress.org/ticket/8474#comment:31).

**Comment by fernandotellado** [comment]
Thank you for the update @mikachan :)

**Comment by mikachan** [comment]
Thank you for testing!

**Comment by mikachan** [comment]
I'm going to close this as there is already a fix in BuddyPress 10.5.0.
