### ISSUE TITLE
How to improve TT3 system font appearance?

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentythree#260]
I realize this has been discussed before, and despite all previous arguments, the current font appearance looks far from ideal in retina screens: rough and, in my opinion, not helping in readability at all.

Here's a screen recording of the difference in the font appearance with font smoothing.

https://user-images.githubusercontent.com/65220155/194298999-d32e9766-bc5b-4a22-9e98-a00b26fe53af.mp4

I'd like to reopen up this discussion in order to get to a good final result.

**Comment by jasmussen** [comment]
Even if choosing the font-smoothing type isn't likely to be built into global styles, it seems perfectly fine to apply it in `style.scss` if it fits the theme well. To an extent, it's an ideal use-case for the stylesheet, and I'd see no problem including it.

**Comment by mikachan** [comment]
I understand the reasons listed here, however, I do have a few reasons against including this CSS:

#### We currently aren't including any CSS
One of the biggest advantages of building a block theme and using the latest Gutenberg features is that we're able to provide a low-code theme that's more accessible to many types of users. This includes limiting the amount of CSS we include and relying on Gutenberg to provide it. As such, we haven't included any CSS for this theme yet. 

It also means that we don't need to include a functions.php file, which again emphasises that TT3 is part of a new generation of low-code themes that no longer require a functions.php file or custom CSS.

#### This is only an optimisation for macOS
The `-webkit-font-smoothing` and `-moz-osx-font-smoothing` properties only work on macOS, so we are only optimising the font appearance for some users (according to a [wiki article](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems), only 6% of users). 

If we had already added some custom CSS, perhaps it wouldn't matter as much. But because of the above, I don't believe this is a good enough reason to introduce extra code.

#### It is generally not recommended
I think it's worth noting that there are many articles arguing why it shouldn't be used, as mentioned [here](https://github.com/WordPress/twentytwentythree/pull/155):

https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/
https://ui.dev/rwd/articles/font-smoothing

The original `font-smooth` property was also removed from the [CSS specification](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth), which I believe is partly why the [specific macOS](https://caniuse.com/font-smooth) properties exist.

The biggest issue for me here is the addition of extra code and files. We've managed to avoid custom CSS so far, so it seems a shame to include it now.

Some links for more context:
- Initial discussion for TT3: https://github.com/WordPress/twentytwentythree/issues/1
- Some additional ideas of how to address this in TT3: https://github.com/WordPress/twentytwentythree/pull/37
- Issue for adding font-smoothing support in Gutenberg: https://github.com/WordPress/gutenberg/pull/36092, and linked PR: https://github.com/WordPress/gutenberg/pull/36092

**Comment by jasmussen** [comment]
> This is only an optimisation for macOS
> It is generally not recommended

This is true, and one of the reasons why the block editor itself doesn't come with it. But in the category of progressive enhancements, it doesn't really hurt or have any downsides. In that light, I appreciate the simple fact that it makes Bea happier with the rendition of her vision.

> We currently aren't including any CSS

There's a simplicity and purity to this, agreed. But I also don't think it's problematic to include a functions.php file just for the stylesheet — would there be any performance hit to this? As a "starter theme", I could also see the presence of the functions.php file as a point of recognition for developers getting started: yes, such a file still works for block themes. You just don't have to put anything in there. 

These are not strong opinions, honestly, I appreciate arguments on all sides, and I'll happily defer to this group to decide. But I did want to boost the weight of the original argument. Details matter, and we should take them seriously, even if it's only one platform. In that light, it's not a question of one small and insignificant CSS property against strong arguments to its omission. It's a matter of a legitimate design concern to be weighed against the theoretical benefit of omitting a single PHP file from the directory.

**Comment by beafialho** [comment]
Thank you @mikachan and @jasmussen for your two cents here!

> so we are only optimising the font appearance for some users

That is true, still I'd be very happy if that small percentage of users had a better experience.

> One of the biggest advantages of building a block theme and using the latest Gutenberg features is that we're able to provide a low-code theme that's more accessible to many types of users.
> It also means that we don't need to include a functions.php file, which again emphasises that TT3 is part of a new generation of low-code themes that no longer require a functions.php file or custom CSS.

Could you elucidate me on how a low-code theme is more accessible to users? How does it improve the user experience?

Improving this seems quite essential to me — the theme needs to work well but also look well —, so even if we're not using this bit of CSS, I am open to try another approach and use the font Inter instead, as was previously suggested, given that we're using it in other variations.

**Comment by mikachan** [comment]
> would there be any performance hit to this? 

I don't believe there's a performance hit, but I do think it makes the theme look more approachable. Perhaps we could include a note in the readme or dev notes that the functions.php is still compatible with this theme.

> Could you elucidate me on how a low-code theme is more accessible to users? How does it improve the user experience?

Low-code themes are more accessible to people who have less coding experience, so the barrier to entry for creating a theme (and therefore a WordPress website) is lowered. I think this sits well alongside the overall goals of Gutenberg.

> I am open to try another approach and use the font Inter instead

The issue with using Inter is that it relies on loading font files, whereas the system font stack tells the browser to use whichever system font is already included with the operating system. Using the system font stack has great performance benefits, and I think it's a good choice for the base theme.

**Comment by mtias** [comment]
The main issue here is that the editor and the front-end are going to look different, which is going to be confusing for users. It seems we should reconcile that and be pragmatic over idealistic. It's more important for the visual experience to be good and consistent than to avoid a custom CSS file. If it's just those two lines it could even just be a style block in the header rather than a separate file. I think it's also fine to include Inter by default, provided people can still select the system stack if they want to?

**Comment by scruffian** [comment]
Some quotes from that article:

>Applying antialiasing instead of subpixel rendering makes the fonts less crisp
>The sharpness of subpixel rendered text makes long portions of body text more readable

When placed alongside this observation:

> The -webkit-font-smoothing and -moz-osx-font-smoothing properties only work on macOS, so we are only optimising the font appearance for some users

The issue to me is that what we are doing is optimizing for our own use case (because we're all using webkit on OSX), and neglecting the experience for the majority of users. If the fonts don't look good with subpixel rendering disabled then lets modify them so that the look better for everyone.

This is also an accessibility issue: https://www.w3.org/WAI/RD/2012/text-customization/p7.html. The decision whether to enable/disable subpixel rendering one should be a user one made at a system level, not something that the theme defines. 

As a default theme I believe TT3 should be encouraging best practices across the web. Font smoothing is not an open standard, so I think that we should avoid it.

This debate reminds me a bit of when we used to add custom CSS to style user's scrollbars - we can make scrollbars look very funky and interesting if we want to, but just because we can doesn't mean we should :)

**Comment by mtias** [comment]
That article is from 2012, ten years in screen resolution and density improvements. Also wp-admin and the editor are already setting font smoothing and the discrepancy is a bigger deal than anything else discussed, IMO.

**Comment by scruffian** [comment]
If that's the case then maybe WordPress should provide it by default for all themes?

**Comment by mikachan** [comment]
I can't see where this is being applied in the site editor. I can see the post editor and wp-admin are setting font-smoothing to `subpixel-antialiased`, which most browsers will default to anyway according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth).

I believe the intended display for TT3 is achieved using the `antialiased` setting, which disables subpixel rendering.

**Comment by scruffian** [comment]
On the post editor I see: -webkit-font-smoothing: subpixel-antialiased;
On the site editor I don't see any font smoothing.

**Comment by mikachan** [comment]
Closing as the theme has been merged into the WordPress Core SVN repository and is no longer maintained on GitHub.
