### ISSUE TITLE
Consider adding button visited styles

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#288]
While testing a separate issue, I learnt that the button in the file block has a [default visited text color that is white.](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/file/style.scss#L34)
This makes it inconsistent with other buttons.

Untested, but I think adding a default "visited" style in theme.json would override the block default.

**Comment by mikachan** [comment]
Really good spot! I think I've found a fix by applying a default colour to all buttons in the file block.

**Comment by peterfabian** [comment]
Is it possible that this change broke visited buttons for some styles? E.g. like here:

https://user-images.githubusercontent.com/2207451/198293193-958030d2-5817-4313-bb2d-be65bfdb8f36.mov

The second button links to a visited page on Jurassic Ninja with `6.1-RC3-54697` over here:
https://worldwide-parrotfish.jurassic.ninja/2022/10/27/title/

Edit: interestingly, I cannot replicate this in incognito. That's odd. 
Edit2: Actually, that's probably because it doesn't save any history. The same happens in Firefox.

**Comment by mikachan** [comment]
Thanks, @peterfabian, good catch! This is related to this change I think. I've got a potential fix here: https://github.com/WordPress/twentytwentythree/pull/296

**Comment by mikachan** [comment]
Created a trac ticket for the above: https://core.trac.wordpress.org/ticket/56928
