### ISSUE TITLE
Call to action pattern: Top border is not centered and too long on front end

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#295]
When adding the TT3 CTA pattern to a page, the short vertical horizontal line that's above the other contents appears fine in the editor, but is too long and shifted over to the right on the front end.

### To replicate

- Add the "call to action" pattern at the top of the Featured patterns list to a page.
- View the pattern in the editor:

<img width="1511" alt="Edit_Page_“Patterns”_‹_Twenty_Twenty-Three_Testing_—_WordPress" src="https://user-images.githubusercontent.com/7662449/197574990-9075404d-3464-4578-9b50-c2aef20b4adf.png">

### Result

View the pattern on the front end:

<img width="1329" alt="Patterns_–_Twenty_Twenty-Three_Testing" src="https://user-images.githubusercontent.com/7662449/197575162-ffef81f4-2f2b-4be0-b0be-1e0dbef36964.png">

Note how the line is too far to the right and too long.

### Expected

The front end should match the editor.

WP 6.1-RC2-54653
Gutenberg 14.3.1 
TT3 - files downloaded from GitHub today

**Comment by mikachan** [comment]
I believe the longer line that is right-aligned is correct according to the designs, however, I can see this is different from what's in the editor.

It looks like the separator block has a fixed width of 100px in the editor, but I thought this may have been fixed by https://github.com/WordPress/gutenberg/pull/44640, as it's being included in theme.css. Looking into this further...

**Comment by mikachan** [comment]
I've attempted a fix for this here: https://github.com/WordPress/gutenberg/pull/45351

I've pushed where I've got up to so far in case it prompts any ideas. Will come back to this later on.

**Comment by mikachan** [comment]
Closing as the theme has been merged into the WordPress Core SVN repository and is no longer maintained on GitHub.
