### ISSUE TITLE
Home template: match the Figma

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentythree#43]
Currently the home template is a query block list-style view. It should match the Figma mockup:

![home](https://user-images.githubusercontent.com/5375500/184420034-60f958c9-d44e-4e10-ba23-4220871fc3e3.png)

**Comment by carolinan** [comment]
<del>1. Is there a design also for the paginated result? -I would like to know if the image and heading is meant to show on page two, or if they outside the query.</del>
Without adding CSS:
-There is no way to hide content on the paginated results.
-Looking at the archive page, the pagination is below the posts, -it is not possible to hide this pagination conditionally.

2. There is no **valid** way to place the query pagination block next to the "Latest posts" text, because its only valid parent is the query loop. There is a work around, but it also means that users who does not know HTML (or block markup) can not replicate this design themselves.

**Comment by carolinan** [comment]
If both the blog heading "mindblown" and the "latests posts", are headings -and they probably should be... then we end up with the post titles being H4. That might be correct, but it sort of goes against the gut feeling, because I think these titles are more important.

**Comment by beafialho** [comment]
We can perhaps simplify and remove "Latest Posts":

<img width="542" alt="Captura de ecrã 2022-08-22, às 10 01 49" src="https://user-images.githubusercontent.com/65220155/185882975-33a6acee-445b-4489-b0c5-029eeb01fbab.png">

**Comment by carolinan** [comment]
I tried using [is_paged()](https://developer.wordpress.org/reference/functions/is_paged/) in a pattern to output different query paginations on the home page and page two (/page/2/), but it did not work, it always returns false.
That means that page 2+ would have the same text "Read All Posts" and that is why I recommend using the same pagination as on the archive. _Or no pagination... but I think that would potentially be unexpected and confusing to users._

**Comment by beafialho** [comment]
Good point! We can have pagination:

<img width="593" alt="Captura de ecrã 2022-08-23, às 08 39 56" src="https://user-images.githubusercontent.com/65220155/186100372-607140b0-b1eb-446c-a6e9-47c9797f8006.png">
